#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Renders the two brand assets the graphical installer draws, from the
# two the designers hand over.
#
#     ./packaging/make-brand-assets.sh
#
#     src/branding/zepos-logo.svg      ->  src/branding/zepos-wordmark.png
#     src/branding/zepos-wallpaper.png ->  src/branding/zepos-backdrop.png
#
# Both results are committed, the same way iso/profile-release/grub/
# themes/ carries committed PNGs regenerated by iso/make-boot-theme.sh.
# Run this after changing either source; tests/installer/test_branding.py
# fails if a result has drifted from what it was made from.
#
# WHY THE INSTALLER GETS ITS OWN COPIES OF WHAT THE BOOT MENU ALREADY HAS
#     Because they have to LOOK like the same screen. The boot menu is
#     seen a minute before the installer, on the same machine, and the
#     handover is the moment a distribution either feels like one thing
#     or like two programs that happen to share a colour.
#
#     So the numbers here are iso/make-boot-theme.sh's numbers, not
#     numbers that resemble them:
#
#       petrol #0D3D47 under a gradient to #092A31, the constellation
#       texture at 12% over the top of it, the texture built by
#       mirroring one logo-free band of the wallpaper onto itself.
#
#     tests/iso/test_boot_theme.py measures the boot menu's copy and
#     tests/installer/test_branding.py measures this one, both against
#     the same thresholds.
#
# WHY A PNG WORDMARK WHEN THE PACKAGE ALSO SHIPS THE SVG
#     Two reasons, both measured on 10.08.2026.
#
#     LAYOUT. Gtk.Picture.new_for_filename() takes the file's own size as
#     the widget's natural size - 700x400 for this SVG - and then neither
#     setting is right. can_shrink(True) lets the layout propose sizes
#     below natural, and while the surrounding box works out its own
#     minimum it proposes -1; something along that path subtracts, GTK is
#     handed a size below -1, and every build logs
#
#         Gtk-CRITICAL: gtk_widget_measure: assertion 'for_size >= -1'
#
#     which tests/installer/test_gui_headless.py fails on. can_shrink
#     (False) silences it by making 700x400 binding, which is larger than
#     the window. A texture that is already the right size has no such
#     negotiation.
#
#     LOADERS. On this machine gdk-pixbuf hands SVG decoding to glycin,
#     which runs the loader inside bwrap. In a sandboxed environment -
#     the test harness, and plausibly a live medium - the spawn fails
#     with "Could not spawn the following command. Is the used binary
#     available? bwrap ..." and the logo silently disappears. GTK's own
#     PNG path involves none of that.
#
#     The SVG stays in the package. It is the source this renders from.
set -euo pipefail

readonly REPO="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly BRANDING="$REPO/src/branding"

# installer/gui/branding.py's MARK_HEIGHT, and 26.8% of the height of a
# 1080-line boot menu divided by this wordmark's own aspect ratio - the
# same share of the screen the menu gives it. Kept in step by
# tests/installer/test_branding.py, which reads both.
readonly MARK_HEIGHT=122

# The backdrop is rendered once at 1080 and scaled by GTK to whatever the
# window is, exactly as GRUB scales its own copy.
readonly BACKDROP_W=1920
readonly BACKDROP_H=1080

# The band of the wallpaper that carries no wordmark, and the opacity
# iso/make-boot-theme.sh settled on. Both are explained there; changing
# one here without changing it there is how the two screens stop
# matching.
readonly BAND_H=330
readonly TEXTURE_ALPHA=0.12

command -v magick >/dev/null || {
    echo "make-brand-assets.sh: ImageMagick (magick) is not installed" >&2
    exit 1
}

for source in zepos-logo.svg zepos-wallpaper.png; do
    [[ -f "$BRANDING/$source" ]] || {
        echo "make-brand-assets.sh: no $BRANDING/$source" >&2
        exit 1
    }
done

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# -background none keeps the transparency; the header draws it on the
# backdrop. -strip drops the timestamp ImageMagick would otherwise write,
# so an unchanged source renders to a byte-identical PNG and the commit
# is empty.
magick -background none "$BRANDING/zepos-logo.svg" \
    -resize "x$MARK_HEIGHT" -depth 8 -strip "$BRANDING/zepos-wordmark.png"

magick "$BRANDING/zepos-wallpaper.png" -crop "1920x${BAND_H}+0+0" +repage \
    "$work/band.png"
magick "$work/band.png" \( "$work/band.png" -flip \) -append "$work/tile.png"

magick -size "${BACKDROP_W}x${BACKDROP_H}" "xc:#0D3D47" \
    \( -size "${BACKDROP_W}x${BACKDROP_H}" gradient:"none-#092A31" \) \
    -gravity center -composite \
    \( "$work/tile.png" -write mpr:tile +delete \
       -size "${BACKDROP_W}x${BACKDROP_H}" tile:mpr:tile \
       -alpha set -channel A -evaluate multiply "$TEXTURE_ALPHA" +channel \) \
    -gravity north -composite \
    -alpha off -depth 8 -define png:color-type=2 -strip \
    "$BRANDING/zepos-backdrop.png"

magick identify "$BRANDING/zepos-wordmark.png" "$BRANDING/zepos-backdrop.png"
