#!/usr/bin/env python3
"""
fetch_icons.py - Fetches Nerd Font icons and creates icons_db.py
Separate Python file for proper debugging and IDE support
"""

import re
import os
import sys
import urllib.request

# Add current directory to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Has to follow the sys.path line above: paths.py is a sibling of this
# file and is not importable before it.
from paths import SYSTEM_ROOT_ENV

# Import icon definitions from separate SSOT file
try:
    from icon_definition import ICON_DEFINITIONS

    print(f"✓ Loaded {len(ICON_DEFINITIONS)} icon definitions from icon_definitions.py")
except ImportError as e:
    print(f"ERROR: Could not import icon_definitions.py: {e}")
    print(f"Current directory: {os.getcwd()}")
    print(f"Script directory: {os.path.dirname(os.path.abspath(__file__))}")
    print(f"Files in directory: {os.listdir(os.path.dirname(os.path.abspath(__file__)))}")
    sys.exit(1)


def download_nerd_fonts_css():
    """Download Nerd Fonts CSS file"""
    url = "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/css/nerd-fonts-generated.css"
    css_file = "/tmp/nerd-fonts.css"

    print("Downloading Nerd Fonts CSS...")
    try:
        urllib.request.urlretrieve(url, css_file)
        print("✓ Downloaded CSS")
        return css_file
    except Exception as e:
        print(f"ERROR: Failed to download CSS: {e}")
        sys.exit(1)


def parse_css_icons(css_file):
    """Parse icons from CSS file"""
    with open(css_file, 'r') as f:
        css_content = f.read()

    # Parse icons: .nf-fa-clock_o:before { content: "\f017"; }
    pattern = r'\.nf-([\w-]+)-([\w_]+):before\s*{\s*content:\s*"\\([0-9a-fA-F]+)"'
    matches = re.findall(pattern, css_content)

    icons = {}
    for prefix, name, unicode_hex in matches:
        nf_name = f"nf-{prefix}-{name}"
        try:
            char = chr(int(unicode_hex, 16))
            icons[nf_name] = char
        except ValueError:
            print(f"Warning: Could not parse {nf_name} with hex {unicode_hex}")

    print(f"✓ Found {len(icons)} icons in CSS")
    return icons


def validate_and_build_icons(css_icons):
    """Validate icon definitions against CSS and build final icon dict"""
    missing_icons = []
    found_icons = {}

    # Check for duplicate keys
    keys_seen = {}
    for key, nf_name in ICON_DEFINITIONS.items():
        if key in keys_seen:
            print(f"ERROR: Duplicate key found: {key} -> {keys_seen[key]} vs {nf_name}")
        keys_seen[key] = nf_name

    for key, nf_name in ICON_DEFINITIONS.items():
        if nf_name in css_icons:
            found_icons[key] = css_icons[nf_name]
        else:
            missing_icons.append((key, nf_name))
            # Spezielle Fallbacks für bekannte Probleme
            if nf_name == "nf-fa-chain_broken":
                found_icons[key] = "⚠"  # Warning symbol als Fallback
            else:
                found_icons[key] = "?"

    # Report
    if missing_icons:
        print(f"\n⚠️  WARNING: {len(missing_icons)} icons not found:")
        for key, nf_name in missing_icons[:10]:
            print(f"   - {key}: {nf_name}")
        if len(missing_icons) > 10:
            print(f"   ... and {len(missing_icons) - 10} more")

    return found_icons, missing_icons


def generate_icons_db(found_icons, missing_icons):
    """Generate icons_db.py content"""
    output = f'''#!/usr/bin/env python3
"""
Central icon definitions for all configs
Auto-generated by fetch_icons.py - DO NOT EDIT MANUALLY!

Total icons: {len(found_icons)}
Missing icons: {len(missing_icons)}
"""

# All icons in a single dictionary - NO DUPLICATES!
icons = {{
'''

    # Add all icons sorted by key
    for key in sorted(found_icons.keys()):
        icon_char = found_icons[key]
        nf_name = ICON_DEFINITIONS[key]
        if icon_char == "?":
            output += f'    "{key}": "?",  # MISSING: {nf_name}\n'
        else:
            output += f'    "{key}": "{icon_char}",  # {nf_name}\n'

    output += '''}

# Der eine Name, unter dem die Sammlung gelesen wird.
#
# Hier standen fuenf: WAYBAR_ICONS, HYPRLAND_ICONS, APP_ICONS,
# EXTRA_ICONS und ALL_ICONS, alle auf DASSELBE Woerterbuch, dazu ein
# ICON_GROUPS mit denselben fuenf Schluesseln. Es gab nie fuenf Gruppen -
# es gab eine Sammlung und fuenf Namen dafuer, und `list --group waybar`
# druckte dieselben 389 Zeichen wie `list --group apps`.
#
# Der erste Name nannte ausserdem ein Programm, das es seit dem
# 11.08.2026 nicht mehr gibt.
ALL_ICONS = icons

def get_icon(name: str, fallback: str = "?") -> str:
    """Get an icon by name with optional fallback"""
    return icons.get(name, fallback)

# Validation function
def validate_icons():
    """Check for missing icons"""
    missing = [k for k, v in icons.items() if v == "?"]
    if missing:
        print(f"⚠️  Warning: {len(missing)} icons are missing:")
        for icon in missing[:5]:
            print(f"   - {icon}")
        if len(missing) > 5:
            print(f"   ... and {len(missing) - 5} more")
    return len(missing) == 0

if __name__ == "__main__":
    validate_icons()
    print(f"Total icons: {len(icons)}")
'''

    return output


def main():
    """Main function"""
    print("=== FETCHING ICONS AND CREATING icons_db.py ===")

    # Download CSS
    css_file = download_nerd_fonts_css()

    # Parse icons
    css_icons = parse_css_icons(css_file)

    # Validate and build
    found_icons, missing_icons = validate_and_build_icons(css_icons)

    # Generate output
    output = generate_icons_db(found_icons, missing_icons)

    # Write file
    # template_processor.py imports icons_db from the directory it sits
    # in, so the database has to be written there and nowhere else. The
    # environment override exists for a packaging run building into a
    # staging directory; falling back to system_root() instead would
    # point every checkout run at /usr/share/zepos, which a developer
    # cannot write to and should not have to.
    root = os.environ.get(SYSTEM_ROOT_ENV) or os.path.dirname(
        os.path.abspath(__file__))
    output_path = os.path.join(root, 'icons_db.py')
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(output)

    # Cleanup
    os.remove(css_file)

    # Summary
    print(f"\n✓ Created {output_path}")
    print(f"✓ {len(found_icons)} icons defined")
    print(f"✓ {len(found_icons) - len(missing_icons)} icons found")
    if missing_icons:
        print(f"⚠️  {len(missing_icons)} icons missing (marked with ?)")

    print("\n=== DONE ===")
    print(f"Run 'python3 {output_path}' to validate")


if __name__ == "__main__":
    main()